---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-plane-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kairosconfigs
  - kairosconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters/status
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kairoscontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kairoscontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kairoscontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockermachines
  - kairosfleetmachines
  - kubevirtmachines
  - metal3machines
  - vspheremachines
  verbs:
  - create
  - get
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - dockermachines/status
  - dockermachinetemplates
  - kairosfleetmachines/status
  - kairosfleetmachinetemplates
  - kubevirtmachines/status
  - kubevirtmachinetemplates
  - metal3machines/status
  - metal3machinetemplates
  - vspheremachines/status
  - vspheremachinetemplates
  - vspherevms
  verbs:
  - get
